### ISSUE TITLE
Newest Nightly

### ISSUE THREAD

**Issue by BoogieHasFun** [BMBF/resources#10]
Syncing doesn't work. So no songs even work. Playlist tab doesn't work. Syncing never finished.

**Comment by BoogieHasFun** [comment]
Comment: Might need to play first..

**Comment by acpass** [comment]
it doesn't work. The button of sync to BS is always red that I can't add songs to the game.

**Comment by happyplacetraveler** [comment]
Found same - always shows red but never syncs.  Also, queue button won't sync to any type.  Finally, on mods, switches aren't displaying correctly every time.

**Comment by Tqxo** [comment]
Nightlies aren't made for song loading. Unless you're a mod developer you should probably wait until the state release.

**Comment by BoogieHasFun** [comment]
Don't use nightly builds.
