### ISSUE TITLE
Are you guys working on a new version for bmbf

### ISSUE THREAD

**Issue by Gael0008** [BMBF/resources#9]
With the new update of beat saber bmbf won't work.

**Comment by luboszima** [comment]
I'm curious too.

**Comment by luboszima** [comment]
On my Oculus Quest 2, have still 1.13.2 version, but my friend just bought Beat Saber and of course downloaded newest version 1.13.5 ... I guess we have to wait to new release BMBF, or is possible downgrade Beat Saber?

**Comment by SilkDev** [comment]
I've been trying to make BMBF work for so long. So it's because it's not updated yet !

**Comment by BoogieHasFun** [comment]
> On my Oculus Quest 2, have still 1.13.2 version, but my friend just bought Beat Saber and of course downloaded newest version 1.13.5 ... I guess we have to wait to new release BMBF, or is possible downgrade Beat Saber? 

Just get your 1.13.2 apk and put it on his Quest 2 like normal but you import the 1.13.2 apk with bmbf.

**Comment by ProtocolNebula** [comment]
I just did it wrong... I've updated without make an APK backup, I will try to ask to some friend a backup... but hope this will be fixed soon.

**Comment by FranciscoRibeiro03** [comment]
Just as a heads up, sharing apks with other people is considered piracy

**Comment by ProtocolNebula** [comment]
Oh, nevermind, I know it.

In fact, I found a backup of the correct version inside BMBF data folder, so I already have the game again.

**Comment by BoogieHasFun** [comment]
> > On my Oculus Quest 2, have still 1.13.2 version, but my friend just bought Beat Saber and of course downloaded newest version 1.13.5 ... I guess we have to wait to new release BMBF, or is possible downgrade Beat Saber? 
> 
> Just get your 1.13.2 apk and put it on his Quest 2 like normal but you import the 1.13.2 apk with bmbf.

Meant to say Sidequest.

**Comment by BoogieHasFun** [comment]
> Just as a heads up, sharing apks with other people is considered piracy

But will it effect your modding experience on 1.13.2 because your friend shared a apk with you? Also piracy is illegal but not too illegal for going to a prison, because cops have better things to do.

**Comment by ProtocolNebula** [comment]
> > Just as a heads up, sharing apks with other people is considered piracy
> 
> But will it effect your modding experience on 1.13.2 because your friend shared a apk with you? Also piracy is illegal but not too illegal for going to a prison, because cops have better things to do.

Seems to be related to the game EULA declaration, but is stupid if you already have bought the game.

Facebook and their incoherent things.

**Comment by jeremygovi** [comment]
Just to answer the main question, maybe this could help (yes, they are working on it): https://github.com/darknight1050/questui

**Comment by kingman1232** [comment]
any time table on when its done just wondeing

**Comment by cedarcreektest** [comment]
@chickgael i think you can close this now

**Comment by christopherweinhardt** [comment]
@chickgael i think you can close this now because there's a nightly build out

**Comment by BoogieHasFun** [comment]
New Nightly, don't use as if custom songs **DO NOT WORK** Yet.

Maybe because I'm being dumb it's not working c:

**Comment by mathsmathsmaths** [comment]
> Just as a heads up, sharing apks with other people is considered piracy

Eh not if both parties (recipient and sender) already bought the rights to the software

**Comment by BoogieHasFun** [comment]
beat saber downgrade available

**Comment by Ectalite** [comment]
But multiplayer does not work on 1.13.2 ? (It says I have to update)

**Comment by BoogieHasFun** [comment]
> But multiplayer does not work on 1.13.2 ? (It says I have to update)

Beattogether exists for a reason.

**Comment by Ectalite** [comment]
Even with beattogether, I have the same error.

**Comment by FranciscoRibeiro03** [comment]
You should ask for help on the BeatTogether Discord server, as this is not the appropriate place to help you...
